### ISSUE TITLE
eagle-eye_Darwin_arm64  v0.1.3 has a virus warning!

### ISSUE THREAD

**Issue by andreaswittmann** [brainboard/eagle-eye#1]
This binary shows two virus warnings on VirusTotal

[eagle-eye_Darwin_arm64](https://github.com/brainboard/eagle-eye/releases/download/v0.1.3/eagle-eye_Darwin_arm64)
<img width="1504" alt="2024-09-14_15-23-05" src="https://github.com/user-attachments/assets/4a19258b-720d-4ef1-a7ca-905ba9b7cb32">

**Comment by esdantunes** [comment]
I used the virus total to analyse the URL and no issues appears. 
https://www.virustotal.com/gui/url/3cf318e09bcbe7bfbc62ad9cb65f3e95f5d1b3f638775e7ec3231b7fe895dbf9?nocache=1

<img width="1725" alt="image" src="https://github.com/user-attachments/assets/167010f3-7b87-495f-98ac-881288afb461">

I also downloaded the file and submitted it, this is the result:
https://www.virustotal.com/gui/file/cf934a23cc8cbac1640baf67dcc495e65ac74ce2c7e931e7f0273cbc8dc5cb10

<img width="1662" alt="image" src="https://github.com/user-attachments/assets/b6b25765-8c6a-44d2-b5f1-f18f49751546">
